# Changes here will be overwritten by Copier
_commit: 973c39c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: tkp-aliases
project_description: Alias for fsspec-pydantic
project_name: pydantic-fsspec
python_version_primary: '3.11'
team: the pydantic-fsspec authors
